const String stripePublishableKey =
    "pk_test_51RFYbWGdiXwaVHHaCXDpyoWiPOJwFPscrAjasNZJBYBWtadfXZrKYlN3i7GRbAUAry9F9w90fDC4drUtqg7NZ2aM00LHSaTjvZ";
const String stripeSecretKey =
    "sk_test_51RBy8VEUlVKujITusgjKVRvLqAfznM2fbBPJsIiH2mvDTgOGqMynVFzNdqdYklpIjgLsYQTFyeUuDttOdP2NGbe300ZL3PqajL";
